### ISSUE TITLE
Snapshotting

### ISSUE THREAD

**Issue by ChrisMcKee** [yreynhout/AggregateSource#24]
I'm dissecting the code base and I'm assuming the snapshots are sorta following the memento pattern but I can't actually work out from the tests how within this code base its supposed to work.

I can see it follows similar implementations to others Ive seen (ISnapshotable on aggregate / methods to pull and push data to set state)
```
public void RestoreSnapshot(object state)
    {
      var agg = (MyAggregateSnapshotPoco)state;
      /* mapping data back to agg */
    }

    public object TakeSnapshot()
    {
      return MyAggregateSnapshotPoco{map agg in};
    }
``` 

I can't see any logic around storing the memento if version is greater than zero and mod 10 (or similar); 
Is there a reason for SnapshotableRepository being a different thing to the repository storing snapshots? I'm guessing the SnapshotableRepository storage as stream should result in a different ident (snapshot_id or something) to avoid conflicting with the aggregate stream but its not enforced (the tests dont clear this up as the names it uses follow the same prefix). 

I was wondering if I was misunderstanding the usage as it seems you'd need both and the methods between the two are similar due to the interface but it makes usage less obvious.

Any explanation would be greatly appreciated; I'm looking at various implementations alongside our existing and trying to understand the thought process behind it 😄

**Comment by yreynhout** [comment]
@ChrisMcKee The motivation is fairly simple. The bulk of the repositories in AggregateSource are collection oriented, and thus for reading only. The UnitOfWork is what collects things to persist at the end (if they've changed obviously and preferably only 1 thing). That said, AggregateSource does not make any attempt at abstracting the writing / appending to a stream. The motivation for that is, there are so many ways you could do that, it wouldn't feel right to put into a library. Hence why you're not seeing any usage of taking a snapshot and the persistence there-of. In retrospect I seldomly use the repository implementations anymore nor the core of aggregate source itself. I use its building blocks, the event router and recorder, abstracting the restoring from events and taking events, restoring from a snapshot and taking a snapshot and compose those into a bespoke solution depending on what the team is used to from a terminology point of view and how mature they are, whether they use collection or persistence oriented repositories, etc ... I'm going to reboot aggregate source in the future, but it will contain a lot less than what it contains today, especially in the repository space, also shedding the need for inheritance (preferring composition). It's just a matter of finding the time :/
