### ISSUE TITLE
No Sagas?

### ISSUE THREAD

**Issue by thomaseyde** [yreynhout/AggregateSource#27]
How do you implement a saga with AggregateSource? I would like something like Jonathan Oliver's [implementation](http://blog.jonathanoliver.com/cqrs-sagas-with-event-sourcing-part-ii-of-ii/):

```
public interface ISaga
{
    Guid Id { get; }
    long Version { get; } // for optimistic concurrency

    void Transition(object message);

    ICollection GetUncommittedEvents();
    void ClearUncommittedEvents();

    ICollection GetUndispatchedMessages();
    void ClearUndispatchedMessages();
}

```

**Comment by yreynhout** [comment]
@thomaseyde you don't - this is not something AS was designed for. Granted, on the surface it may look very similar.

**Comment by thomaseyde** [comment]
Fair enough. Are there any recepies? Are we supposed to write our own implementation? Maybe someone should build a "SagaSource" spinoff?

**Comment by yreynhout** [comment]
You could implement a custom saga using the EventRouter and EventRecorder classes. That'd be a very quick way of going about it.
